---

- name: Update packages
  apt:
    name: "*"
    state: latest
    force_apt_get: true
  tags: packages

- name: Add PHP repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present
  tags: packages

- name: Checking PHP version
  shell: "php -v | head -1 | cut -c 5-7"
  register: php_installed_version
  ignore_errors: true
  changed_when: false
  tags: packages

- name: Remove any other PHP versions
  when: php_installed_version.rc != 2 and (php_installed_version.stdout|float != php_version|float)
  apt:
    name: "php*"
    state: absent
  tags: packages

- name: Install PHP and required modules
  apt:
    name:
      - "php{{ php_version }}"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-json"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-sqlite3"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-xml"
    state: present
  tags: packages

- name: Install MCrypt extension for PHP < 7.2
  apt:
    name: "php{{ php_version }}-mcrypt"
    state: present
  when: php_installed_version.stdout|float < 7.2
  tags: packages
